#!/usr/bin/perl

use Digest::MD5;
use DBI;
use HTML::Parser;
use LWP::Simple;
use XML::Twig;

use strict;



my $content = get(
    'http://www.flickr.com/services/feeds/photos_public.gne?id=30378931@N00&format=rss_200'
);

my ( $map );

XML::Twig->new(
    twig_handlers => {
        item => sub {
            $map->{$_->field( 'link' )}->{$a} = $_->field( $a );
        }
    }
)->parse( $content );

my $dbh = DBI->connect(
    'dbi:mysql:tumble:localhost',
    'tumble'
) || die( $DBI::errstr );

my $parser = HTML::Parser->new(
    api_version => 3,
    start_h     => [ \&img_handler, "self,tagname,attr" ],
    report_tags => [ qw( img ) ]
);

map { $parser->parse( get( $_ ), ); } keys %{$map};

sub img_handler {
    my ( $self, $tag, $attr ) = @_;

    my $link = $_;

    return unless $tag eq "img";
    return unless ( $attr->{'width'} > 280 ) && ( $attr->{'height'} > 200 );

    my $image = unpack( 'H*', get($attr->{'src'}) );

    my $md5 = Digest::MD5->new();

    $md5->add( $image );

    my $md5sum = $md5->b64digest();

    my $exists = $dbh->do( qq{
        SELECT imageID FROM image WHERE md5sum = '$md5sum'
    } ) || die( $DBI::errstr );

    unless ( $exists == 1 ) {
        my $sth = $dbh->prepare( qq{
            INSERT INTO image (
                title, link, url, md5sum
            ) VALUES (
                ?,?,?,?
            )
        } ) || die( $DBI::errstr );

        my $rv = $sth->execute(
            $attr->{'alt'}, $link, $attr->{'src'}, $md5sum
        ) || die( $DBI::errstr );
    }
}
