name: Run Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.38'
        
    - name: Install Dependencies
      run: cpanm JSON LWP::Simple Test::More
      
    - name: Run Tests
      run: make test
